# Generated by Django 4.2.2 on 2023-09-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='price_prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otArea', models.FloatField()),
                ('MSZoning', models.CharField(max_length=255)),
                ('BldgType', models.CharField(max_length=255)),
                ('ExterQual', models.CharField(max_length=255)),
                ('OverallQual', models.CharField(max_length=255)),
                ('GarageType', models.CharField(max_length=255)),
                ('CentralAir', models.CharField(max_length=255)),
                ('Heating', models.CharField(max_length=255)),
                ('predicted_price', models.FloatField()),
            ],
        ),
    ]
